application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /upload
  script: image.application

- url: /img.*
  script: image.application

- url: /account.*
  script: account.application

- url: /.*
  script: question.application


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
